### ISSUE TITLE
Milestone 2 discussion

### ISSUE THREAD

**Issue by christopheralex** [UBC-MDS/airpyllution#19]
- [x] Convert API call response to dataframe individually.
- [x] Write test cases for the chart functions.
- [x] Create R directories.
- [x] Write R function docstring.
- [x] Get back on Python difficulties before 18th Jan.
